# Generated by Django 5.2.1 on 2025-06-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='users/'),
        ),
    ]
