# Generated by Django 5.2.1 on 2025-06-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_news_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='views_count',
        ),
    ]
